on: 
    workflow_call:
        secrets:
            tf_api_token:
                required: true
            aws_access_key:
                required: true
            aws_secret_access_key:
                required: true
            gcp_credentials_json:
                required: true
            azure_secret_key:
                required: true
            vpn_secret:
                required: true
jobs:
    deploy-infrastructure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Infra code
              uses: actions/checkout@v3
              with:
                repository: 'LabregoPT/movie-analyst-infra'
            - name: Create JSON file with the GCP Credentials
              run: printenv AUTH > 'gcp_key.json'
              env:
                  AUTH: ${{ secrets.gcp_credentials_json }}
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                cli_config_credentials_token: ${{ secrets.tf_api_token}}
            - name: Initialize Terraform
              run: terraform init
            - name: Plan execution
              run: terraform plan -input=false
              env:
                TF_VAR_aws_access_key: ${{ secrets.aws_access_key }}
                TF_VAR_aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
                TF_VAR_gcp_credentials_file: "./gcp_key.json"
                TF_VAR_AZURE_SECRET_KEY: ${{secrets.azure_secret_key}}
                TF_VAR_VPN_SECRET: ${{secrets.vpn_secret}}
            - name: Apply execution
              run: terraform apply -auto-approve -input=false
              env:
                TF_VAR_aws_access_key: ${{ secrets.aws_access_key }}
                TF_VAR_aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
                TF_VAR_gcp_credentials_file: "./gcp_key.json"
                TF_VAR_AZURE_SECRET_KEY: ${{secrets.azure_secret_key}}
                TF_VAR_VPN_SECRET: ${{secrets.vpn_secret}}
            - name: Save output to JSON file
              run: terraform output -json > ./infra-output.json
            - name: Upload infra output artifact
              uses: actions/upload-artifact@v3
              with:
                name: infra-output
                path: ./infra-output.json